# Generated by Django 4.2.9 on 2026-03-17 12:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_id', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('avatar_url', models.URLField(blank=True)),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField(blank=True)),
                ('token_expiry', models.DateTimeField(blank=True, null=True)),
                ('primary_calendar_id', models.CharField(default='primary', max_length=255)),
                ('calendar_sync_enabled', models.BooleanField(default=True)),
                ('last_calendar_sync', models.DateTimeField(blank=True, null=True)),
                ('calendar_sync_token', models.TextField(blank=True)),
                ('gmail_import_enabled', models.BooleanField(default=False)),
                ('gmail_import_label', models.CharField(default='Calendar-App-Desktop', max_length=100)),
                ('last_gmail_import', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='google_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
